spring:
  config:
    activate:
      on-profile: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    instance-id: discovery-server:8761

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
