spring:
  application:
    name: discovery-server

  main:
    web-application-type: servlet   # 🔴 REQUIRED for Boot 3 + Eureka

eureka:
  client:
    register-with-eureka: false     # server does not register to itself
    fetch-registry: false



# E file anedi 2 YML files with 2 Eureka ports ni set-up cheyali anukunappudu oka master YML file rayali adi ede